{{- if .Values.configurationFiles.apache }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "typo3.fullname" . }}-apache
data:
{{- range $key, $val := .Values.configurationFiles.apache }}
  {{ $key }}: |-
{{ $val | indent 4}}
{{- end }}
{{- end -}}
---
{{- if .Values.configurationFiles.php }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "typo3.fullname" . }}-php
data:
{{- range $key, $val := .Values.configurationFiles.php }}
  {{ $key }}: |-
{{ $val | indent 4}}
{{- end }}
{{- end -}}
---
{{- if .Values.configurationFiles.typo3 }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "typo3.fullname" . }}-typo3
data:
{{- range $key, $val := .Values.configurationFiles.typo3 }}
  {{ $key }}: |-
{{ $val | indent 4}}
{{- end }}
{{- end -}}
