apiVersion: v1
kind: Secret
metadata:
  name: {{ include "typo3.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "typo3.name" . }}
    helm.sh/chart: {{ include "typo3.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  typo3-admin-username: {{ .Values.typo3.adminUsername | b64enc | quote }}
{{- if .Values.typo3.adminPassword }}
  typo3-admin-password:  {{ .Values.typo3.adminPassword | b64enc | quote }}
{{- else }}
  typo3-admin-password: {{ randAlphaNum 10 | b64enc | quote }}
{{- end }}
